BookStoreDashboard/Models/ActionMessage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStoreDashboard.Models
{
    public class ActionMessage
    {
        public string Message { get; set; }
    }
}

BookStoreDashboard/Models/Book/BookDto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookStoreDashboard.Models.Book
{
    public class BookDto
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Genre { get; set; }
        [Required]
        public string Author { get; set; }
        [Required]
        public int Quantity { get; set; }
        [Required]
        public double Price { get; set; }
        public bool IsDeleted { get; set; }
    }
}

BookStoreDashboard/Models/EnumStatus.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStoreDashboard.Models
{
    public enum EnumStatus
    {
        Pending,
        InProcess,
        Delivered
    }
}

BookStoreDashboard/Models/ErrorViewModel.cs
using System;

namespace BookStoreDashboard.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BookStoreDashboard/Models/OrderDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStoreDashboard.Models
{
    public class OrderDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public double FullPrice { get; set; }
        public EnumStatus Status { get; set; }

    }
}

BookStoreDashboard/Models/UpdateOrderDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStoreDashboard.Models
{
    public class UpdateOrderDto
    {
        public int OrderId { get; set; }
        public EnumStatus Status { get; set; }
    }
}

BookStoreDashboard/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStoreDashboard.Models;
using BookStoreDashboard.Models.Book;
using BookStoreDashboard.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookStoreDashboard.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        private readonly IBookService bookService;

        public BookController(IBookService bookService)
        {
            this.bookService = bookService;
        }

        public async Task<IActionResult> Overview()
        {
            var books = await bookService.GetAll();
            return View(books);
        }

        public async Task<IActionResult> Edit(int bookId)
        {
            var book = await bookService.GetById(bookId);
            return View(book);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(BookDto book)
        {
            var result = await bookService.Update(book);
            return RedirectToAction("ActionMessage", "Home", new { Message = result });
        }

        public async Task<IActionResult> UpdateIsDeleted(int bookId, bool status)
        {
            await bookService.UpdateIsDeleted(bookId, status);
            if (status)
            {
                return RedirectToAction("ActionMessage", "Home", new { Message = "Book successfully removed from user display" });
            }
            return RedirectToAction("ActionMessage", "Home", new { Message = "Book successfully recovered for user display" });
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(BookDto book)
        {
            if (ModelState.IsValid)
            {
                bookService.Create(book);
                return RedirectToAction("ActionMessage", "Home", new { Message = "Book successfully created" });
            }
            return View(book);
        }
    }
}

BookStoreDashboard/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BookStoreDashboard.Models;
using Microsoft.AspNetCore.Authorization;

namespace BookStoreDashboard.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Dashboard()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }



        public IActionResult ActionMessage(ActionMessage actionMessage)
        {
            return View(actionMessage);
        }
    }
}

BookStoreDashboard/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStoreDashboard.Models;
using BookStoreDashboard.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BookStoreDashboard.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService orderService;

        public OrderController(IOrderService orderService)
        {
            this.orderService = orderService;
        }
        public async Task<IActionResult> Overview()
        {
            var orders = await orderService.GetAll();
            return View(orders);
        }

        public async Task<IActionResult> Update(int orderId, EnumStatus status)
        {
            var result = await orderService.Update(orderId, status);
            return RedirectToAction("ActionMessage", "Home", new { Message = result });
        }
    }
}

BookStoreDashboard/Views/Book/ActionMessage.cshtml
@model BookStoreDashboard.Models.ActionMessage

<div class="container">
    <br />
    <h3>@Model.Message</h3>
    <br />
    <p class="text-muted">Back to <a asp-action="Overview">overview</a></p>
</div>

BookStoreDashboard/Views/Book/Create.cshtml
@model BookStoreDashboard.Models.Book.BookDto

<h1>Create new book</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Overview">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookStoreDashboard/Views/Book/Edit.cshtml
@model BookStoreDashboard.Models.Book.BookDto

@{
    ViewData["Title"] = "Edit";
}


@if (!string.IsNullOrEmpty(ViewBag.Result))
{
    <h3 class="text-info">@ViewBag.Result</h3>
}
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" class="form-control" hidden />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Overview">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookStoreDashboard/Views/Book/Overview.cshtml
@model List<BookStoreDashboard.Models.Book.BookDto>
@section Styles{
    <link rel="stylesheet" href="~/css/table.css" />
}

<div class="container">
    <br />
    <h3>Book overview</h3>
    <br />
    <a class="btn btn-success" asp-action="Create">Create new book</a>
    <br />
    <br />

    <table class="defaultTable table table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Genre</th>
                <th>Price</th>
                <th>In stock</th>
                <th style="text-align: center;">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var book in Model)
            {
                <tr>
                    <td>@book.Title</td>
                    <td>@book.Author</td>
                    <td>@book.Genre</td>
                    <td>@book.Price</td>
                    <td>@book.Quantity</td>
                    <td style="text-align: center;">
                        <a class="btn btn-primary btn-sm" asp-action="Edit" asp-route-bookId="@book.Id">Edit</a> |
                        @if (book.IsDeleted)
                        {
                            <a class="btn btn-success btn-sm" asp-action="UpdateIsDeleted" asp-route-bookId="@book.Id" asp-route-status="false" onclick="return confirm(`Are you sure you want to recover this book`)">Recover</a>
                        }
                        else
                        {
                            <a class="btn btn-danger btn-sm" asp-action="UpdateIsDeleted" asp-route-bookId="@book.Id" asp-route-status="true" onclick="return confirm(`Are you sure you want to delete this book`)">Delete</a>
                        }
                        | <button class="btn btn-info btn-sm" id="@book.Id" onclick="Toggle(event)">Details</button>
                    </td>
                </tr>

                <tr id="book-@book.Id" class="hide description">
                    <td colspan="6">
                        <b>Description:</b> <br />
                        @book.Description
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts{ 
    <script src="~/js/table.js"></script>
}

BookStoreDashboard/Views/Home/ActionMessage.cshtml
@model BookStoreDashboard.Models.ActionMessage

<div class="container">
    <br />
    <h3>@Model.Message</h3>
    <br />
    <p class="text-muted">Back to <a asp-controller="Home" asp-action="Dashboard">Dashboard</a></p>
</div>

BookStoreDashboard/Views/Home/Dashboard.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <br />
    <h3>Admin dashboard</h3>
    <br />

    <a asp-controller="Book" asp-action="Overview" class="btn btn-success btn-lg">Books</a>
    <a asp-controller="Order" asp-action="Overview" class="btn btn-success btn-lg">Orders</a>
    
</div>

BookStoreDashboard/Views/Order/Overview.cshtml
@model List<BookStoreDashboard.Models.OrderDto>

<div class="container">
    <br />
    <h3>Manage orders</h3>
    <br />

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Adress</th>
                <th>Phone</th>
                <th>Order price</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model)
            {
                <tr>
                    <td>@order.Name</td>
                    <td>@order.Adress</td>
                    <td>@order.Phone</td>
                    <td>@order.FullPrice</td>
                    <td>@order.Status.ToString()</td>
                    <td>
                        @if (order.Status == EnumStatus.Pending)
                        {
                            <a asp-action="Update" asp-route-orderId="@order.Id" asp-route-status="@EnumStatus.InProcess" class="btn btn-primary btn-sm">Set to InProcess</a>
                        }
                        else if (order.Status == EnumStatus.InProcess)
                        {
                            <a asp-action="Update" asp-route-orderId="@order.Id" asp-route-status="@EnumStatus.Delivered" class="btn btn-success btn-sm">Set to Delivered</a>
                        }
                        else
                        {
                            <p class="text-success">Delivered</p>
                        }

                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

BookStoreDashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStoreDashboard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStoreDashboard</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Dashboard">Home</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>